version: 2
jobs:
  build:
    parallelism: 4
    macos:  # indicate that we are using the macOS executor
      xcode: "10.0.0" # indicate our selected version of Xcode
    steps: # a series of commands to run
      - checkout

      - run: ./adify.sh --noconfirm
